 const liftAccessories = {
    "Cabin Accessories": [
      {
        name: "Cabin fan",
        image: "/images/cabin-fan.jpg",
        description: "High-performance ventilation system for elevator cabins ensuring proper air circulation",
        features: ["Energy efficient", "Quiet operation", "Adjustable speed"],
        priceRange: "$150-$300",
      },
      {
        name: "Handrails",
        image: "/images/handrails.jpg",
        description: "Sturdy stainless steel or aluminum handrails for passenger safety and support",
        features: ["Anti-slip surface", "Custom lengths", "Easy installation"],
        priceRange: "$200-$500",
      },
      {
        name: "Mirror panel",
        image: "/images/mirror-panel.jpg",
        description: "Tempered glass mirrors that create an illusion of spaciousness in the cabin",
        features: ["Safety glass", "Custom sizes", "Scratch resistant"],
        priceRange: "$250-$600",
      },
      {
        name: "False ceiling with LED lights",
        image: "/images/led-ceiling.jpg",
        description: "Modern lighting solutions with energy-efficient LEDs for better illumination",
        features: ["Multiple color options", "Dimmable", "Long lifespan"],
        priceRange: "$400-$800",
      },
      {
        name: "Floor tiles / anti-skid flooring",
        image: "/images/elevator-flooring.jpg",
        description: "Durable and slip-resistant flooring options in various designs and materials",
        features: ["Easy maintenance", "Wear resistant", "Custom designs"],
        priceRange: "$300-$700",
      },
      {
        name: "Voice annunciator system",
        image: "/images/voice-annunciator.jpg",
        description: "Audio floor announcement system for visually impaired users",
        features: ["Multiple languages", "Adjustable volume", "Clear audio"],
        priceRange: "$350-$650",
      },
      {
        name: "Cabin display (LCD or LED)",
        image: "/images/cabin-display.jpg",
        description: "Digital display showing current floor and direction of travel",
        features: ["High visibility", "Energy saving", "Custom messages"],
        priceRange: "$500-$900",
      },
    ],
    "Control & Display Systems": [
      {
        name: "COP (Car Operating Panel)",
        image: "/images/cop-panel.jpg",
        description: "Elevator control panel inside the cabin with floor selection buttons",
        features: ["Tactile buttons", "Backlit display", "Durable construction"],
        priceRange: "$450-$850",
      },
      {
        name: "LOP (Landing Operating Panel)",
        image: "/images/lop-panel.jpg",
        description: "Hall call buttons at each floor for summoning the elevator",
        features: ["Weather resistant", "ADA compliant", "LED indicators"],
        priceRange: "$400-$750",
      },
      {
        name: "Digital/LED/LCD display",
        image: "/images/digital-display.jpg",
        description: "Modern floor indicators showing elevator position and direction",
        features: ["Large digits", "Energy efficient", "Multiple display options"],
        priceRange: "$600-$1200",
      },
      {
        name: "Touch or button-based control panel",
        image: "/images/touch-panel.jpg",
        description: "Advanced control interfaces with touch-sensitive or tactile buttons",
        features: ["Intuitive interface", "Custom programming", "Access control"],
        priceRange: "$700-$1500",
      },
      {
        name: "Access control system (card reader, biometric)",
        image: "/images/access-control.jpg",
        description: "Security systems for restricted access to specific floors",
        features: ["RFID compatible", "Biometric options", "Audit trail"],
        priceRange: "$1000-$2500",
      },
    ],
    "Door Accessories": [
      {
        name: "Automatic doors (telescopic/center opening)",
        image: "/images/automatic-doors.jpg",
        description: "Smooth operating door systems with various opening configurations",
        features: ["Fast operation", "Safety sensors", "Low noise"],
        priceRange: "$2000-$5000",
      },
      {
        name: "Manual collapsible door",
        image: "/images/collapsible-door.jpg",
        description: "Traditional manual doors for elevator cabins",
        features: ["Durable construction", "Easy operation", "Safety latches"],
        priceRange: "$800-$2000",
      },
      {
        name: "Vision panel / glass doors",
        image: "/images/glass-doors.jpg",
        description: "Transparent doors or panels allowing visibility into the elevator",
        features: ["Tempered glass", "Frosted options", "Scratch resistant"],
        priceRange: "$1500-$3500",
      },
      {
        name: "Door sensors (infrared or mechanical)",
        image: "/images/door-sensors.jpg",
        description: "Safety devices that prevent doors from closing on obstructions",
        features: ["Reliable detection", "Easy adjustment", "Dual beam"],
        priceRange: "$300-$700",
      },
      {
        name: "Door header motor and controller",
        image: "/images/door-motor.jpg",
        description: "Precision components for smooth door operation",
        features: ["Variable speed", "Soft start/stop", "Low maintenance"],
        priceRange: "$1200-$2800",
      },
    ],
    "Safety Accessories": [
      {
        name: "Overload indicator",
        image: "/images/overload-indicator.jpg",
        description: "System that detects and alerts when elevator exceeds capacity",
        features: ["Accurate measurement", "Visual/audio alarm", "Auto shutdown"],
        priceRange: "$600-$1200",
      },
      {
        name: "Emergency alarm and intercom",
        image: "/images/emergency-intercom.jpg",
        description: "Communication system for emergencies",
        features: ["Two-way communication", "Battery backup", "Auto dial"],
        priceRange: "$500-$1000",
      },
      {
        name: "Emergency stop switch",
        image: "/images/emergency-stop.jpg",
        description: "Safety mechanism to immediately halt elevator operation",
        features: ["Mushroom head", "Locking mechanism", "Bright color"],
        priceRange: "$150-$300",
      },
      {
        name: "Auto-rescue device (ARD)",
        image: "/images/auto-rescue.jpg",
        description: "System that automatically moves elevator to nearest floor during power failure",
        features: ["Battery backup", "Smooth operation", "Manual override"],
        priceRange: "$1500-$3000",
      },
      {
        name: "Fireman switch",
        image: "/images/fireman-switch.jpg",
        description: "Special control mode for fire emergency service",
        features: ["Key operated", "Priority override", "Visual indicator"],
        priceRange: "$400-$800",
      },
      {
        name: "Buffer spring/oil buffer",
        image: "/images/elevator-buffer.jpg",
        description: "Shock-absorbing devices at the elevator pit",
        features: ["Energy absorption", "Durable construction", "Maintenance free"],
        priceRange: "$800-$2000",
      },
      {
        name: "Governor and safety gear",
        image: "/images/governor.jpg",
        description: "Overspeed protection system for elevator cars",
        features: ["Precision mechanism", "Reliable triggering", "Easy inspection"],
        priceRange: "$2500-$5000",
      },
    ],
    "Electrical Accessories": [
      {
        name: "Control panel",
        image: "/images/control-panel.jpg",
        description: "Main control unit managing elevator operation",
        features: ["Microprocessor based", "Fault diagnostics", "Energy saving"],
        priceRange: "$3000-$8000",
      },
      {
        name: "UPS or ARD system",
        image: "/images/ups-system.jpg",
        description: "Uninterruptible power supply for emergency operation",
        features: ["Seamless switchover", "Long battery life", "Automatic testing"],
        priceRange: "$2000-$5000",
      },
      {
        name: "Inverter or VVVF drive",
        image: "/images/inverter-drive.jpg",
        description: "Variable voltage variable frequency drive for smooth operation",
        features: ["Energy efficient", "Soft acceleration", "Compact design"],
        priceRange: "$2500-$6000",
      },
      {
        name: "Main cable and traveling cable",
        image: "/images/traveling-cable.jpg",
        description: "Power and signal transmission cables for elevator operation",
        features: ["Flexible construction", "Durable jacket", "EMI shielded"],
        priceRange: "$800-$2000",
      },
    ],
    "Shaft & Pit Equipment": [
      {
        name: "Guide rails",
        image: "/images/guide-rails.jpg",
        description: "Precision rails that guide the elevator car's movement",
        features: ["High strength steel", "Precision machined", "Corrosion resistant"],
        priceRange: "$1500-$4000",
      },
      {
        name: "Counterweight frame",
        image: "/images/counterweight.jpg",
        description: "Balancing system to reduce motor load",
        features: ["Precise balancing", "Durable construction", "Adjustable weights"],
        priceRange: "$2000-$5000",
      },
      {
        name: "Limit switches",
        image: "/images/limit-switches.jpg",
        description: "Safety devices that prevent overtravel at shaft ends",
        features: ["Positive operation", "Durable contacts", "Easy adjustment"],
        priceRange: "$300-$700",
      },
      {
        name: "Pit ladder",
        image: "/images/pit-ladder.jpg",
        description: "Access ladder for elevator pit maintenance",
        features: ["Anti-slip steps", "Corrosion resistant", "Foldable design"],
        priceRange: "$500-$1200",
      },
      {
        name: "Shaft light",
        image: "/images/shaft-light.jpg",
        description: "Illumination system for elevator shaft",
        features: ["Explosion proof", "Long lifespan", "Motion activated"],
        priceRange: "$200-$500",
      },
    ],
    Miscellaneous: [
      {
        name: "Floor position indicator",
        image: "/images/position-indicator.jpg",
        description: "Displays elevator position in the hoistway",
        features: ["Large display", "Energy efficient", "Multiple styles"],
        priceRange: "$400-$900",
      },
      {
        name: "Braille button panel",
        image: "/images/braille-panel.jpg",
        description: "Tactile buttons for visually impaired users",
        features: ["ADA compliant", "Durable markings", "Backlit buttons"],
        priceRange: "$300-$700",
      },
      {
        name: "Landing bell",
        image: "/images/landing-bell.jpg",
        description: "Audible signal indicating elevator arrival",
        features: ["Adjustable volume", "Pleasant tone", "Durable construction"],
        priceRange: "$150-$350",
      },
      {
        name: "Maintenance tools kit",
        image: "/images/tools-kit.jpg",
        description: "Specialized tools for elevator servicing",
        features: ["Complete set", "Durable tools", "Portable case"],
        priceRange: "$500-$1200",
      },
    ],
  };